# Generated by Django 5.2 on 2025-08-15 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctions_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
