# Generated by Django 5.2 on 2025-08-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auctions_is_active_auctions_winner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=520)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
